experiment:
  # machine setting, optional: cuda, cpu
  device: cuda
  # dataset setting
  dataset_name: UrbanAir
  used_feature_params: ['weather',
               'temperature',
               'humidity',
               'hour',
               'weekday',
               'month',
               'wind_speed',
               'wind_direction']
  feature_process: [ 1, 1, 1, 1, 1, 2, 1, 1 ]
  train_start: [ [ 2014, 5, 1 ], GMT ]
  train_end: [ [ 2015, 2, 16 ], GMT ]
  valid_start: [ [ 2015, 2, 17 ], GMT ]
  valid_end: [ [ 2015, 3, 24 ], GMT ]
  test_start: [ [ 2015, 3, 25 ], GMT ]
  test_end: [ [ 2015, 5, 1 ], GMT ]
#  dataset_name: KnowAir
#  used_feature_params: ['2m_temperature',
#               'relative_humidity+950',
#               'boundary_layer_height',
#               'k_index',
#               'surface_pressure',
#               'total_precipitation',
#               'hour',
#               'weekday',
#               'month',
#               'wind_speed',
#               'wind_direction']
#  feature_process: [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
#  train_start: [ [ 2015, 1, 1 ], GMT ]
#  train_end: [ [ 2016, 12, 31 ], GMT ]
#  valid_start: [ [ 2017, 1, 1 ], GMT ]
#  valid_end: [ [ 2017, 12, 31 ], GMT ]
#  test_start: [ [ 2018, 1, 1 ], GMT ]
#  test_end: [ [ 2018, 12, 31 ], GMT ]
  # progress setting
  save_npy: True
  # model setting
  model_name: NodeSTConv
  # train seed, 0 means random, default:1
  seed: 0
  # dataloader num worker
  num_workers: 12
  # data load into cuda
  use_cuda: True

# general hyperparameters setting
general_hyper_params:
   # 24, 8
  hist_len: 8
  # 24, 8
  pred_len: 8
  # 1024 2048
  batch_size: 2048
  epochs: 50
  exp_times: 5
  weight_decay: 0.0001
  lr: 0.0001
  is_early_stop: True
  early_stop: 5

# model hyperparameters setting
model_hyper_params:
  feature_process: [ 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1 ]
#  feature_process: [ 1, 1, 1, 2, 2, 2, 1, 1 ]
  NodeSTConv:
    hidden_dim: 64
    dropout: 0.3
    alpha: 0.5
    gru_layers: 2
    K: 2

# general filepath
filepath:
  Local:
    dataset_dir: ...
    records_dir: ...
    results_dir: ...
  Linux:
    dataset_dir: ...
    records_dir: ...
    results_dir: ...

# dataset info
KnowAir:
  data_start: [ [ 2015, 1, 1, 0, 0 ], GMT ]
  data_end: [ [ 2018, 12, 31, 21, 0 ], GMT ]
  time_span_hour: 3
  city_num: 184
  feature_params:
    ['100m_u_component_of_wind',
     '100m_v_component_of_wind',
     '2m_dewpoint_temperature',
     '2m_temperature',
     'boundary_layer_height',
     'k_index',
     'relative_humidity+950',
     'relative_humidity+975',
     'specific_humidity+950',
     'surface_pressure',
     'temperature+925',
     'temperature+950',
     'total_precipitation',
     'u_component_of_wind+950',
     'v_component_of_wind+950',
     'vertical_velocity+950',
     'vorticity+950',
     'hour',
     'weekday',
     'month',
     'wind_speed',
     'wind_direction']
CityAir:
  data_start: [ [ 2017, 1, 1, 0, 0 ], GMT ]
  data_end: [ [ 2019, 4, 30, 12, 0 ], GMT ]
  time_span_hour: 1
  city_num: 209
  # Currently don't know the order of parameters and the specific meaning of a parameter
  feature_params:
    ['humidity',
     'rainfall',
     'air_pressure',
     'temperature',
     'wind_speed',
     'wind_direction'
    ]
UrbanAir:
  data_start: [ [ 2014, 5, 1, 0, 0 ], GMT ]
  data_end: [ [ 2015, 5, 1, 23, 0 ], GMT ]
  time_span_hour: 1
  city_num: 30
  feature_params:
    [ 'weather',
      'temperature',
      'humidity',
      'hour',
      'weekday',
      'month',
      'wind_speed',
      'wind_direction']